# Generated by Django 5.2.6 on 2025-10-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emp_id', models.CharField(max_length=10)),
                ('emp_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('position', models.CharField(max_length=100)),
                ('emp_working', models.BooleanField(default=True)),
                ('emp_department', models.CharField(max_length=100)),
                ('emp_address', models.TextField(max_length=300)),
            ],
        ),
    ]
